{{- $values := .Values.staffPortalUi -}}
{{- $context := dict "Values" (merge (deepCopy $values) (dict "global" .Values.global)) "Chart" .Chart "Release" .Release "Files" .Files "Capabilities" .Capabilities -}}
{{- with $context -}}
{{- if .Values.istio.enabled }}
{{- if .Values.istio.gateway.enabled }}
{{- $istioGatewayHostname := include "common.tplvalues.render" (dict "value" .Values.istio.gateway.host "context" $) }}
{{- $mainHostname := include "common.tplvalues.render" (dict "value" .Values.hostname "context" $) }}
{{- $hostname := default $mainHostname $istioGatewayHostname }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.istio.gateway.ingressController "context" $) | nindent 4 }}
  servers:
  {{- if .Values.istio.gateway.httpEnabled }}
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      - {{ $hostname | quote }}
    {{- if .Values.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- end }}
  {{- if .Values.istio.gateway.httpsEnabled }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      - {{ $hostname | quote }}
    tls: {{- include "common.tplvalues.render" (dict "value" (omit .Values.istio.gateway.tls "enabled") "context" $) | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}
